<?php
function kevincaching_menu() {

    $items['mysql/mysqllog'] = array( //this creates a URL that will call this form at "examples/form-example"
        'title' => 'list',
        'description' => 'list',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('kevincaching_admin_data'),
        'access arguments' => array('access content overview'),
        'weight' => -1,
        'file' => 'kevincaching.admin.inc',

    );

    $items['mysql/mysqllog/create'] = array( //this creates a URL that will call this form at "examples/form-example"
        'title' => 'Create',
        'description' => 'Create',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('kevincaching_create'),
        'access arguments' => array('access content overview'),
        'file' => 'kevincaching.create.inc',
    );


    return $items;
}

function kevincaching_menu_view($arg) {

    error_log($arg, 3, "/var/tmp/php-errors.log");
    $data = "china";
    return $data;
}

function kevincaching_form($form, &$form_state) {

    $form['username'] = array(
        '#type' => 'textfield',
        '#title' => t('name'),
    );

    $form['submit_button'] = array(
        '#type' => 'submit',
        '#value' => t('Save'),
    );

    db_query_node();

    return $form;
}


function db_query_node() {
    $nodes = db_query('SELECT * FROM crypto_currencies');

    foreach($nodes as $item) {
        print_r($item->name);
    }
}

function node_admin_content_one($form, $form_state) {
    if (isset($form_state['values']['operation']) && $form_state['values']['operation'] == 'delete') {
        return node_multiple_delete_confirm($form, $form_state, array_filter($form_state['values']['nodes']));
    }

    $form['#submit'][] = 'node_filter_form_submit';
    $form['admin'] = node_admin_nodes();

    return $form;
}

function node_admin_nodes_one() {

    return null;
}