<?php

function kevincaching_menu() {
    $items['mysql/mysqllogone'] = array(
        'title' => 'mysql log kevin',
        'description' => 'mysql log',
        'page callback' => 'form_example_intro',
        'page arguments' => array(t('kevin .', array('!link' => url('examples/menu_example/path_only')))),
        'access callback' => TRUE,
        'expanded' => TRUE,
    );

//    $items['mysql/mysqllog'] = array( //this creates a URL that will call this form at "examples/form-example"
//        'title' => 'Create cryptocurrency', //page title
//        'description' => 'A form to mess around with.',
//        'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
//        'page arguments' => array('kevincaching_form'), //put the name of the form here
//        'access callback' => TRUE
//    );


    $items['mysql/mysqllog'] = array( //this creates a URL that will call this form at "examples/form-example"
        'title' => 'Content',
        'description' => 'Find and manage content.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('kevincaching_admin_data'),
        'access arguments' => array('access content overview'),
        'weight' => -1,
        'file' => 'kevincaching.admin.inc',

    );

    return $items;
}

function kevincaching_menu_view($arg) {

    error_log($arg, 3, "/var/tmp/php-errors.log");
    $data = "china";
    return $data;
}

function kevincaching_form($form, &$form_state) {

    $form['username'] = array(
        '#type' => 'textfield',
        '#title' => t('name'),
    );

    $form['submit_button'] = array(
        '#type' => 'submit',
        '#value' => t('Save'),
    );

    db_query_node();

    return $form;
}

/**
 * Save configuration settings for MY_MODULE_NAME module.
 */
function kevincaching_form_submit($form, &$form_state) {
    variable_set('MY_MODULE_NAME_setting1', $form_state['values']['MY_MODULE_NAME_setting1']);

    drupal_set_message('The MY_MODULE_NAME settings have been saved at '.date("d/m/Y H:i:s"));
}

function db_query_node() {
    $nodes = db_query('SELECT * FROM crypto_currencies');

    foreach($nodes as $item) {
        print_r($item->name);
    }
}

function node_admin_content_one($form, $form_state) {
    if (isset($form_state['values']['operation']) && $form_state['values']['operation'] == 'delete') {
        return node_multiple_delete_confirm($form, $form_state, array_filter($form_state['values']['nodes']));
    }

    $form['#submit'][] = 'node_filter_form_submit';
    $form['admin'] = node_admin_nodes();

    return $form;
}

function hook_views_data() {

}

function node_admin_nodes_one() {

    return null;
}